[package]
name = "mcpi-rs"
version = "0.1.0"
edition = "2018"
authors = ["Caviar-X <caviarx@163.com>"]
description = "Raspberryjuice api in rust version"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]